/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alvesguilherme.fastapi.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;
/**
 * ClienteFornecedor
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-07T08:55:07.825-03:00[America/Sao_Paulo]")

public class ClienteFornecedor {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("razao_social")
  private String razaoSocial = "";

  @SerializedName("nome")
  private String nome = "";

  @SerializedName("cpfcnpj")
  private String cpfcnpj = "";

  @SerializedName("telefone")
  private String telefone = "";

  @SerializedName("email")
  private String email = "";

  @SerializedName("observacao")
  private String observacao = "";

  @SerializedName("grupoeconomico")
  private String grupoeconomico = "";

  @SerializedName("empresa")
  private String empresa = "";

  @SerializedName("fixo")
  private Boolean fixo = false;

  public ClienteFornecedor id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ClienteFornecedor razaoSocial(String razaoSocial) {
    this.razaoSocial = razaoSocial;
    return this;
  }

   /**
   * Get razaoSocial
   * @return razaoSocial
  **/
  public String getRazaoSocial() {
    return razaoSocial;
  }

  public void setRazaoSocial(String razaoSocial) {
    this.razaoSocial = razaoSocial;
  }

  public ClienteFornecedor nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Get nome
   * @return nome
  **/

  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public ClienteFornecedor cpfcnpj(String cpfcnpj) {
    this.cpfcnpj = cpfcnpj;
    return this;
  }

   /**
   * Get cpfcnpj
   * @return cpfcnpj
  **/

  public String getCpfcnpj() {
    return cpfcnpj;
  }

  public void setCpfcnpj(String cpfcnpj) {
    this.cpfcnpj = cpfcnpj;
  }

  public ClienteFornecedor telefone(String telefone) {
    this.telefone = telefone;
    return this;
  }

   /**
   * Get telefone
   * @return telefone
  **/

  public String getTelefone() {
    return telefone;
  }

  public void setTelefone(String telefone) {
    this.telefone = telefone;
  }

  public ClienteFornecedor email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ClienteFornecedor observacao(String observacao) {
    this.observacao = observacao;
    return this;
  }

   /**
   * Get observacao
   * @return observacao
  **/

  public String getObservacao() {
    return observacao;
  }

  public void setObservacao(String observacao) {
    this.observacao = observacao;
  }

  public ClienteFornecedor grupoeconomico(String grupoeconomico) {
    this.grupoeconomico = grupoeconomico;
    return this;
  }

   /**
   * Get grupoeconomico
   * @return grupoeconomico
  **/

  public String getGrupoeconomico() {
    return grupoeconomico;
  }

  public void setGrupoeconomico(String grupoeconomico) {
    this.grupoeconomico = grupoeconomico;
  }

  public ClienteFornecedor empresa(String empresa) {
    this.empresa = empresa;
    return this;
  }

   /**
   * Get empresa
   * @return empresa
  **/

  public String getEmpresa() {
    return empresa;
  }

  public void setEmpresa(String empresa) {
    this.empresa = empresa;
  }

  public ClienteFornecedor fixo(Boolean fixo) {
    this.fixo = fixo;
    return this;
  }

   /**
   * Get fixo
   * @return fixo
  **/

  public Boolean isFixo() {
    return fixo;
  }

  public void setFixo(Boolean fixo) {
    this.fixo = fixo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClienteFornecedor clienteFornecedor = (ClienteFornecedor) o;
    return Objects.equals(this.id, clienteFornecedor.id) &&
        Objects.equals(this.razaoSocial, clienteFornecedor.razaoSocial) &&
        Objects.equals(this.nome, clienteFornecedor.nome) &&
        Objects.equals(this.cpfcnpj, clienteFornecedor.cpfcnpj) &&
        Objects.equals(this.telefone, clienteFornecedor.telefone) &&
        Objects.equals(this.email, clienteFornecedor.email) &&
        Objects.equals(this.observacao, clienteFornecedor.observacao) &&
        Objects.equals(this.grupoeconomico, clienteFornecedor.grupoeconomico) &&
        Objects.equals(this.empresa, clienteFornecedor.empresa) &&
        Objects.equals(this.fixo, clienteFornecedor.fixo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, razaoSocial, nome, cpfcnpj, telefone, email, observacao, grupoeconomico, empresa, fixo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClienteFornecedor {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    razaoSocial: ").append(toIndentedString(razaoSocial)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    cpfcnpj: ").append(toIndentedString(cpfcnpj)).append("\n");
    sb.append("    telefone: ").append(toIndentedString(telefone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    observacao: ").append(toIndentedString(observacao)).append("\n");
    sb.append("    grupoeconomico: ").append(toIndentedString(grupoeconomico)).append("\n");
    sb.append("    empresa: ").append(toIndentedString(empresa)).append("\n");
    sb.append("    fixo: ").append(toIndentedString(fixo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
