/*
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.alvesguilherme.fastapi.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;
/**
 * ClienteFornecedor
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-10-07T08:55:07.825-03:00[America/Sao_Paulo]")

public class ClienteFornecedor {
  @SerializedName("id")
  private Integer id;

  @SerializedName("razao_social")
  private String razaoSocial;

  @SerializedName("nome")
  private String nome;

  @SerializedName("cpfcnpj")
  private String cpfcnpj;

  @SerializedName("telefone")
  private String telefone;

  @SerializedName("email")
  private String email;

  @SerializedName("observacao")
  private String observacao;

  @SerializedName("grupoeconomico")
  private Integer grupoeconomico;

  @SerializedName("empresa")
  private Integer empresa;

  @SerializedName("fixo")
  private Boolean fixo;

  /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setRazaoSocial(String razaoSocial) {
    this.razaoSocial = razaoSocial;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public void setCpfcnpj(String cpfcnpj) {
    this.cpfcnpj = cpfcnpj;
  }

  public void setTelefone(String telefone) {
    this.telefone = telefone;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public void setObservacao(String observacao) {
    this.observacao = observacao;
  }

  public void setGrupoeconomico(Integer grupoeconomico) {
    this.grupoeconomico = grupoeconomico;
  }

  public void setEmpresa(Integer empresa) {
    this.empresa = empresa;
  }

  public void setFixo(Boolean fixo) {
    this.fixo = fixo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClienteFornecedor clienteFornecedor = (ClienteFornecedor) o;
    return Objects.equals(this.id, clienteFornecedor.id) &&
        Objects.equals(this.razaoSocial, clienteFornecedor.razaoSocial) &&
        Objects.equals(this.nome, clienteFornecedor.nome) &&
        Objects.equals(this.cpfcnpj, clienteFornecedor.cpfcnpj) &&
        Objects.equals(this.telefone, clienteFornecedor.telefone) &&
        Objects.equals(this.email, clienteFornecedor.email) &&
        Objects.equals(this.observacao, clienteFornecedor.observacao) &&
        Objects.equals(this.grupoeconomico, clienteFornecedor.grupoeconomico) &&
        Objects.equals(this.empresa, clienteFornecedor.empresa) &&
        Objects.equals(this.fixo, clienteFornecedor.fixo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, razaoSocial, nome, cpfcnpj, telefone, email, observacao, grupoeconomico, empresa, fixo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClienteFornecedor {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    razaoSocial: ").append(toIndentedString(razaoSocial)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    cpfcnpj: ").append(toIndentedString(cpfcnpj)).append("\n");
    sb.append("    telefone: ").append(toIndentedString(telefone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    observacao: ").append(toIndentedString(observacao)).append("\n");
    sb.append("    grupoeconomico: ").append(toIndentedString(grupoeconomico)).append("\n");
    sb.append("    empresa: ").append(toIndentedString(empresa)).append("\n");
    sb.append("    fixo: ").append(toIndentedString(fixo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
